name: Eesh Chilukalapalli
author: Eesh Chilukalapalli
description: Welcome to my website!
github: https://www.github.com/eesh
twitter: https://www.twitter.com/eeshlikhith
facebook: https://www.facebook.com/eeshlikhith
linkedin: https://www.linkedin.com/eesh-chilukalapalli-
email: eesh.likhith@gmail.com
home_title: Hello! Welcome to my personal website :)

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
